- app/routes/virtual/v3/docs/$.tsx
The "Edit on GitHub" link on the Virtual docs was pointing to the `Table` repo. 
Should close https://github.com/TanStack/virtual/issues/320
> Fix "Edit on GitHub" link on Virtual docs

- app/components/Docs.tsx
Very simple fix I found is getting rid of `display: grid` on mobile as it wasn't required, at least for now.
Grid is required on larger screens (`lg` unit) and I added it back there.
This fixes the weird scrolling bug on docs page.
> fix: docs page scrolling on mobile because of unnecessary grid usage

- app/components/Docs.tsx
- app/routes/query/v4/docs/$.tsx
PR to fix #20.
The content width has been constrained to max-w-3xl (768px). This also fixes the aside ad being "squashed" and the page overflowing horizontally:
> Adjust sizing of main content area for readability

- app/components/CodeBlock.tsx
Some languages like `ts` weren't working. It would be better to use the languages exported from Prism dynamically.
> Fix supported languages

- app/components/Docs.tsx
Current behaviour (elements overlapping):
Fixed:
> add z-index to prevent elements overlapping

- app/components/Docs.tsx
- app/routes/query/v4/docs/examples/$.tsx
- app/routes/router/v4/docs/examples/$.tsx
- app/routes/table/v8/docs/examples/$.tsx
- app/routes/virtual/v3/docs/examples/$.tsx
Based on this conversation: https://twitter.com/tan_stack/status/1566932860841340929
Current:
The code sandboxes don't grow in height because the Docs parent is a block on smaller devices. This makes it almost unusable for smaller devices or a laptop side by side.
After: 
Also removed a "Spacer" block that is intended to make room for the prev / next nav buttons. On mobile it just created unneeded space between the Subscriber box and the code sandbox.
I think the experience could be even a bit better by creating an alternative subscriber box on smaller devices. Something horizontal instead of vertical.
Note: This should affect all code examples across tanstack, not just the table ones. (Query etc.)
> Improve code sample spacing on smaller screens

- app/routes/query/v4/index.tsx
- app/routes/router/v4/index.tsx
- app/routes/virtual/v3/index.tsx
Fix what I assume is a small typo for the partners email links on three pages (https://github.com/search?q=org%3ATanStack+parters&type=code).
Let me know if you need me to rebase or if you squash merge!
> fix: typo email partners

- app/utils/documents.server.ts
`mdx-bundler` does not support table in markdown, which causes docs broken.
https://github.com/kentcdodds/mdx-bundler/issues/81
Add remark-gfm plugin into MdxBundler option so that it generates a table for markdown.
> Add remark-gfm plugin to mdx option to support table in markdown

- app/styles/app.css
This turns elements like the scrollbar and native unstyled inputs into native browser dark mode.
closes #39
> Switch all native elements to native dark mode

- app/components/CodeBlock.tsx
Aliasing `markup` as `vue` syntax highlight which is `good-enough`.
Removing lang fallback in jsx as it's already defaulted before.
This can also be aliased in a better way with a small refactor to split code `tag` and `lang` passed to the component, so if you do not like this solution, please let me know.
> feat: alias markup as vue syntax highlight

- app/routes/query/v4/index.tsx
This actually requires `solid` example to be renamed to `basic` without `-typescript` suffix
> chore: enable vue and solid examples

- app/components/Mdx.tsx
Probably a minor thing, but I noticed that `undefined` was being rendered into all code blocks and it was quick and easy to fix, so I fixed it.
| | |
| - | - |
| BEFORE | ![Screenshot_20221031_134311](https://user-images.githubusercontent.com/15232461/199074001-a9eea2b8-7b82-44f7-b067-526e572ade24.png) |
| AFTER | ![Screenshot_20221031_134515](https://user-images.githubusercontent.com/15232461/199074399-64d2372f-39e8-48a3-a2c7-d1a715c9928d.png) |
Here's a more in-context screenshot:
> fixes `undefined` rendered into className

- app/components/Docs.tsx
Hides the bytes signup on mobile so the Stackblitz iframe can go full height.
> Fix layout issue on mobile

- app/components/Docs.tsx
The current framework switcher position in mobile and tablet view prevents it from being selectable. Here is a video of the current behavior. 
https://user-images.githubusercontent.com/45807386/208134155-a1b334ec-0b2a-46dd-9cce-86c5280c8b63.mov
This PR just just places the framework switcher at the top of the menu. 
https://user-images.githubusercontent.com/45807386/208134376-92151a9c-98a5-4551-a4dd-4ecea468ae79.mov
This change doesn't affect anything on desktop view since the sidebar menu for it is a separate component. Please let me know if you have any questions, concerns regarding this change and I'll be sure to answer them ASAP.
> (fix: docs) - Switcher unselectable on mobile/tablet

- app/utils/documents.server.ts
This PR adds two content replacement mechanism for documentation files (`origin`) that are referencing other files (`target`).
You can reference another file by adding `ref` directive in front-matter (ex. `ref: docs/react/quick-start.md`).
1. Simple string replacement
- Add `replace` directive to front-matter in `origin` file with a `key-value` map of strings that should be replaced in the `target` file.
```
replace: {
'replace this': 'with this',
}
```
2. Content section replacement
- Section token is a pair of tokens following this pattern (This is a comment syntax for markdown files)
```
[//]: # (Example)
example section content
[//]: # (Example)
```
- Mark sections that can be replaced in the `target` file with section tokens
- Provide new content for specific sections in `origin` …
> feat: content replacement mechanism for referenced files

- app/utils/documents.server.ts
Changing token used to perform content replacement due to prettier.
When formatting document token gets changed and would be broken, therefore it's better to align it to the format prefered by prettier
> fix: change replacement token

- app/root.tsx
Based on the [@docsearch/css](https://docsearch.algolia.com/docs/styling/) package[ _variables.css](https://github.com/algolia/docsearch/blob/2c64362067376a76575b7b5131972f71c920a406/packages/docsearch-css/src/_variables.css#L51).
A quick way to add dark mode to the DocSearch component.
Can obviously be improved, but I'd suggest to leave it until there's some work done on allowing to toggle between the themes as a user. @TkDodo needs his dark mode docs search when he's steaming!
> ✨ feat(Search): add data-theme attr to document

- app/routes/router/v1/index.tsx
I noted that the example on the homepage is no longer working because the `kitchen-sink` example no longer exists.
> fix(homepage): sandbox url is out of sync with github path

- app/routes/query/$.tsx
- app/routes/query/$version/index.tsx
@TkDodo 
- redirect old adapters pages to proper url with latest version
- show svelte adapter sandbox on main query page
> docs: add redirects for old adapters pages

- app/styles/app.css
Code blocks on TanStack sites currently fail accessibility tests due to this issue:
https://dequeuniversity.com/rules/axe/3.5/scrollable-region-focusable
The reason is that the content is not visible when the code block overflows, like so:
This style change makes the code block wrap so that it does not overflow, like this:
This fixes the issue and makes it much more usable on mobile I think.
> fix: a11y - code blocks should have keyboard access

- app/components/CodeBlock.tsx
- package.json
- yarn.lock
This PR updates from `prism-react-renderer` v1.3.5 to v2.0.6. Importantly, the v2 API supports [custom languages](https://github.com/FormidableLabs/prism-react-renderer#custom-language-support).
I've temporarily added markup as an alias for svelte - in a subsequent PR (once I've made changes to the tanstack query docs), I'll add [prism-svelte](https://github.com/pngwn/prism-svelte).
> feat: Update prism-react-renderer

- app/components/BytesForm.tsx
- app/components/Doc.tsx
- app/components/Docs.tsx
- app/components/DocsCalloutBytes.tsx
- app/components/DocsCalloutQueryGG.tsx
- app/routes/query/$version/index.tsx
- app/styles/app.css
This PR:
- Adds sidebar to docs pages at medium+ viewport widths
- query.gg callout on Query docs pages
- Bytes callout on all other docs pages
- Fixed, dismissible callout remains for small viewports
- Improves readability of docs pages
- Increases main column font size
- Adds max-width to container to restrict line length
- Reduces margin for headlines within prose
- Adjusts placement of Bytes logo in Bytes signup
**Query docs sidebar (large view):**
**Other docs sidebar (large view):**
**Query docs sidebar (medium):**
**Query docs fixed callout open & closed (small view):**
<p><img width="974" alt="Screen Shot 2023-10-25 at 3 30 41 PM" src="https://github.com/TanStack/tanstack.com/assets/871315/e3aaf1e4-3913-43ba-bdd6-a1ba663ae62d"></p>
**Adjusted Bytes logo placement before & after:**
> Docs sidebar callout + style tweaks

- app/routes/router.v1._index.tsx
This adds back the missing space in the Router landing sub-header.
> fix missing space in Router landing

- app/routes/router.v1._index.tsx
This PR fixes some spacing issue on the TanStack Router home page.
> Fix Spacing on TanStack Router Home Page

- app/routes/form.$version.docs.$.tsx
- app/routes/form.$version.docs.framework.$framework.$.tsx
- app/routes/form.$version.docs.framework.$framework.tsx
- app/routes/store.$version.docs.$.tsx
- app/routes/store.$version.docs.framework.$framework.$.tsx
- app/routes/store.$version.docs.framework.$framework.tsx
Some of the pages for `TanStack/Form` and `TanStack/Store` had wrong titles:
> Fix the page titles for Form and Store

- app/routes/ranger.v1._index.tsx
Text in the Tanstack Ranger home page was referring to it as "Router" instead of "Ranger"
https://tanstack.com/ranger/v1#:~:text=Partners-,ROUTER,-YOU%3F
> Fix: Change "Router" to "Ranger" in Ranger homepage partner section

- app/components/CodeBlock.tsx
- app/components/Doc.tsx
- app/components/RenderMarkdown.tsx
- app/routes/blog.$.tsx
- app/routes/blog._index.tsx
- app/routes/form.$version.docs.$.tsx
- app/routes/query.$version.docs.$framework.$.tsx
- app/routes/ranger.tsx
- app/routes/ranger.v1.docs.$.tsx
- app/routes/ranger.v1.docs.examples.$.tsx
- app/routes/router.tsx
- app/routes/router.v1.docs.$.tsx
- app/routes/router.v1.docs.examples.$.tsx
- app/routes/store.$version.docs.$.tsx
- app/routes/store.$version.docs.framework.$framework.$.tsx
- app/routes/table.v8.docs.$.tsx
- app/routes/virtual.v3.docs.$.tsx
- app/utils/docs.ts
- app/utils/documents.server.ts
- package.json
- pnpm-lock.yaml
This replaces [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) with [react-markdown](https://github.com/remarkjs/react-markdown). No MDX features are actually used, and mdx-bundler was extremely difficult to integrate with certain remark/rehype plugins. It also seems a bit excessive to need esbuild to serve plain `.md` docs.
This is Remix Vite ready too 🚀
> feat: Migrate from mdx-bundler to react-markdown

- app/components/RenderMarkdown.tsx
YouTube videos in markdown files weren't using the full container width like they were with MDX. This PR adds the `w-full` tailwind class to iframes.
> fix: Markdown iframe (youtube video) width

- app/routes/form.$version.docs.framework.$framework.examples.$.tsx
- app/routes/query.$version.docs.$framework.examples.$.tsx
- app/routes/ranger.v1.docs.examples.$.tsx
- app/routes/ranger.v1.tsx
- app/routes/router.v1.docs.examples.$.tsx
- app/routes/router.v1.tsx
- app/routes/store.$version.docs.framework.$framework.examples.$.tsx
- app/routes/table.v8.docs.examples.$.tsx
- app/routes/table.v8.tsx
- app/routes/virtual.v3.docs.examples.$.tsx
- app/routes/virtual.v3.tsx
All logic is taken from `app/routes/router.v1.docs.examples.$.tsx`. Uses a stackblitz iframe as the default example renderer. Also has links to the github source and codesandbox.
> feat: Demo all examples on StackBlitz

- README.md
Lately several people have asked about editing the `TanStack/form` docs and previewing them locally in the `#form` channel on Discord, so we updated `CONTRIBUTING.md` in that repo to address this: https://github.com/TanStack/form/pull/537.
@crutchcorn suggested that rather than doing this in every project, we could add the instructions to this one, and then reference it everywhere else.
What do you think?
> Update the README.md with info about editing the docs locally

- app/components/DocsLayout.tsx
Currently, for the v2 layout (form/store), the react and "core" docs have text coloured, while other frameworks have their background coloured. I think this was a bug, so I've changed it so text is coloured - here is the difference.
> fix: Framework text colour with v2 docs layout

- app/routes/form.$version.docs.tsx
- app/routes/query.$version.docs.tsx
- app/routes/store.$version.docs.tsx
- app/routes/table.$version.docs.tsx
- app/routes/virtual.$version.docs.tsx
Fixes the error that occurs for invalid versions (e.g. /table/v9/docs) described on #153
> fix: Invalid versions redirect to latest

- app/components/DocsLayout.tsx
- app/components/DocsLogo.tsx
- app/projects/form.tsx
- app/projects/query.tsx
- app/projects/ranger.tsx
- app/projects/router.tsx
- app/projects/store.tsx
- app/projects/table.tsx
- app/projects/virtual.tsx
- app/routes/form.$version._index.tsx
- app/routes/form.$version.docs.tsx
- app/routes/query.$version._index.tsx
- app/routes/query.$version.docs.tsx
- app/routes/ranger.$version._index.tsx
- app/routes/ranger.$version.docs.tsx
- app/routes/router.$version._index.tsx
- app/routes/router.$version.docs.tsx
- app/routes/store.$version._index.tsx
- app/routes/store.$version.docs.tsx
- app/routes/table.$version._index.tsx
- app/routes/table.$version.docs.tsx
- app/routes/virtual.$version._index.tsx
- app/routes/virtual.$version.docs.tsx
- app/utils/config.ts
- tanstack-docs-config.schema.json
- Removed `v2`, `frameworkConfig` and `versionConfig` options on `<DocsLayout />`
- Moved `createLogo` logic into `<DocsLogo />` component
- Replaced `gradientText` with `colorFrom` and `colorTo`, which are now also applied to `<DocsLayout />`
- Marked `frameworkMenus` as required field in `config.json`
- Fixed missing docs when the framework saved in localStorage isn't available for that project
> refactor: Simplify docs logic, fix loading framework from localStorage

- app/routes/query.$version.docs.$.tsx
Fixes #156, https://github.com/TanStack/query/issues/6772
> fix: Redirect old query docs path

- app/routes/query.$version.docs.$.tsx
Without this fix, all the /query/[version]/docs/[vue/react]/reference pages redirect to /query/[version]/docs/framework/react/overview, which breaks Algolia Search.
See these urls:
- https://tanstack.com/query/latest/docs/react/reference/QueryClient 
- https://tanstack.com/query/latest/docs/vue/reference/QueryClient
> Fix Algolia for the /query/latest/docs/react/reference pages

- app/routes/query.$version.docs.$.tsx
- app/routes/query.$version.docs.framework.$framework.$.tsx
https://github.com/TanStack/tanstack.com/pull/160 fixed this route:
- https://tanstack.com/query/latest/docs/react/reference/QueryClient
but broke this one:
- https://tanstack.com/query/latest/docs/react/reference/hydration
When I was making that PR I was unaware of the fact that not all `reference` docs are in same directory in `tanstack/query`. We currently have three directories named "reference":
- docs/framework/react/reference
- docs/framework/vue/reference
- docs/reference
> Try fixing algolia search for Query again

- app/routes/form.$version.docs.framework.$framework.$.tsx
- app/routes/query.$version.docs.$.tsx
- app/routes/query.$version.docs.framework.$framework.$.tsx
- app/routes/ranger.$version.docs.framework.$framework.$.tsx
- app/routes/router.$version.docs.framework.$framework.$.tsx
- app/routes/store.$version.docs.framework.$framework.$.tsx
- app/routes/table.$version.docs.framework.$framework.$.tsx
- app/routes/virtual.$version.docs.framework.$framework.$.tsx
- Generalises the pattern introduced in #162
- Also fixes old vue path redirects for query (https://github.com/TanStack/query/issues/6770)
> fix: Redirect all missing framework-specific routes to core routes

- app/utils/config.ts
Currently, if you navigate to a framework route like `/query/latest/docs/framework/vue/guides/ssr`, but your previously selected framework (which gets saved in local storage) was a different framework (e.g. react), it will render the correct document, but the sidebar will show the local storage framework's options.
This hook prioritises the framework in the URL over the framework in local storage when choosing the sidebar docs to display.
> fix: Show correct framework sidebar

- app/components/DocsLayout.tsx
- app/projects/store.ts
We have docs for Angular now for TanStack Store (see https://github.com/TanStack/store/pull/41).
> Add Angular to the framework picker for Store

- app/routes/query.$version.docs.framework.$framework.examples.$.tsx
By default, StackBlitz runs Angular CLI applications with an Angular template. WebContainers work much better however. [StackBlitz are looking into changing this default](https://github.com/stackblitz/core/issues/2957) In the meantime this commit adds the `preset=node` parameter to the StackBlitz embed which makes sure a WebContainers template is used (as described in the linked StackBlitz issue).
I confirmed all other framework examples already run as WebContainers even without the parameter so nothing will change there. Once the default template changes, the parameter can be removed.
The Angular examples based on the Angular CLI are currently non-functional in Stackblitz. See screenshots for the Angular infinite query example with and without `preset=node`
> fix(angular-query): WebContainers template for Stackblitz examples fixes broken Angular examples

- app/routes/_index.tsx
The Query's mention to Angular currently exists on `tanstack.com/query` but not on the global TanStack homepage, so I simply added it.
_Before_
_After_
> Add Angular to Query's description

- app/routes/ranger.$version._index.tsx
- app/routes/virtual.$version._index.tsx
fixes #174
- `examples/${framework}/simple` doesn’t exist in any of the `react`, `svelte`, or `vue` examples folders
- `examples/${framework}/fixed` does exist in all of the framework example folders and seems like the equivalent to “simple”
> Update stackblitz embed src from /simple → /fixed

- app/components/DocsLayout.tsx
- app/components/Select.tsx
- app/projects/form.ts
- app/projects/query.ts
- app/projects/ranger.ts
- app/projects/router.ts
- app/projects/store.ts
- app/projects/table.ts
- app/projects/virtual.ts
The `available` field now uses type `Array<{ label: string; value: string; logo?: string}>` rather than `Record<string, { label: string; value: string; logo?: string }>`
This was the most pain-free way to allow a project to have no frameworks (i.e. tanstack/config will be able to `export const frameworks = []`, and no framework selector will appear).
> refactor: `<Select />` takes array of options rather than object of objects

- app/components/DocsLayout.tsx
- app/utils/config.ts
- tanstack-docs-config.schema.json
Fixes #172 
Project PRs:
- Query: https://github.com/TanStack/query/pull/7087
- Table: https://github.com/TanStack/table/pull/5404
- Router: https://github.com/TanStack/router/pull/1294
- Virtual: https://github.com/TanStack/virtual/pull/687
- Form: https://github.com/TanStack/form/pull/622
- Ranger: https://github.com/TanStack/ranger/pull/89
- Store: https://github.com/TanStack/store/pull/53
- Config: https://github.com/TanStack/config/pull/67
> feat: Update project docs sidebar config

- app/components/SponsorPack.tsx
When hovering over a sponsor link/logo, the transition snaps.
Move the transition to the GPU by adding the CSS declaration `will-change: transform;`.
This makes the transition smoother and fixes the snapping.
https://github.com/TanStack/tanstack.com/assets/69698193/c057b0b5-31cb-42b5-a095-711f64b09d65
> style: enhance sponsor link hover transition

- .prettierignore
- app/routes/__root.tsx
Restores the previous functionality of having the DocSearch component respond to the user's color-schema preference.
Also, added a function to the script to watch for changes to the preference, and update the `data-theme` attribute accordingly.
Something might have changed from our previous implementation, but now DocSearch's default styles only recognize the `data-theme` attribute when it's being set on the HTML document (and not the body), so these changes reflect that.
> fix: dark mode for the docsearch component

- app/routes/$libraryId.$version.docs.framework.$framework.examples.$.tsx
- app/routes/$libraryId.$version.docs.index.tsx
- app/routes/$libraryId.index.tsx
Fixes:
* Incorrect title and description on the example pages.
Chore:
* Passing in the params to the redirect throws on couple pages in their loaders.
> fix: title and descriptions on the docs examples route and using the params fields when throwing redirects in the loader

- app/components/RenderMarkdown.tsx
- app/styles/app.css
- package.json
- pnpm-lock.yaml
Fix #213
For these changes to work we need to make more changes in the markdown files as well. [doc link](https://shiki.style/packages/transformers#transformernotationdiff)
> fix:213  Adding transformerNotationDiff to handle diff present in the markdown

- app/libraries/store.ts
I found incorrect ogImage link in `store.ts` and fixed like this :)
```typescript
export const storeProject: Library = {
id: 'store',
name: 'TanStack Store',
cardStyles: `shadow-xl shadow-stone-700/20 dark:shadow-lg dark:shadow-stone-500/20 text-stone-500 dark:text-stone-400 border-2 border-transparent hover:border-current`,
to: '/store',
tagline: `Framework agnostic data store with reactive framework adapters`,
description: `The immutable-reactive data store that powers the core of TanStack libraries and their framework adapters.`,
// ogImage: 'https://github.com/tanstack/config/raw/main/media/repo-header.png',  // before
ogImage: 'https://github.com/tanstack/store/raw/main/media/repo-header.png', // fixed
badge: 'new',
bgStyle: 'bg-stone-700',
textStyle: 'text-stone-500',
repo: …
```
> docs: Fix incorrect ogImage link

- app/routes/_libraries.table.$version.index.tsx
- app/utils/sandbox.ts
Simply trying to get the docs to open the main file devs will be interested in by default
> feat: show main sandbox files on load

- app/routes/_libraries.index.tsx
- package.json
- pnpm-lock.yaml
this PR solves this:
- The searchbox in Tanstack (homepage only) closes when the user clicks on any part of it (caused by two searchboxes rendered on the hp)
- some logs were printed on click
> fix: remove extra searchbox from hp

- app/routes/$libraryId.$version.docs.framework.$framework.examples.$.tsx
- app/utils/sandbox.ts
This attempts to be at least 90% accurate and open up the main file in the example instead of the README file when a sandbox is being viewed.
> feat: open up relevant file on sandbox load on all example pages

- app/routes/_libraries.form.$version.index.tsx
- app/routes/_libraries.query.$version.index.tsx
- app/routes/_libraries.table.$version.index.tsx
The Angular examples for
- Query
- Form
- Table
show errors and do not run because StackBlitz is not configured to always use Webcontainers. For Angular StackBlitz will then default to their [legacy EngineBlock technology](https://github.com/stackblitz/core/issues/2957) which does not work for recent Angular versions.
This PR adds a parameter to make sure Webcontainers is used instead.
> fix: angular examples

- app/components/Doc.tsx
- app/styles/app.css
Currently, all headings extracted from the markdown files are wrapped in anchor tags.
Since anchor tags have a display property of `inline`, when there are adjacent headings and no content to separate them, it causes the headings to collapse onto one another into a single line. See the screenshot below.
The easiest fix for this, without having to use specific CSS selectors, is to set the `display: grid;` on the outer block containing the markdown content. This fixes the bug and restores order to world 🙌🏼. See the screenshot below.
> fix: headings collapsing when there is no content to separate them

- app/utils/documents.server.ts
> [!IMPORTANT]
> This change should have zero impact on the current status of the docs, instead it should make it easier for us to manage images in the future.
From this discussion with Tanner: https://discord.com/channels/719702312431386674/1252133993172697098
Right now, when any of the TanStack projects move to a new major version, we keep all the content of the previous major versions in their own branches. Since we generally have a "main" branch, old branches (v1, v2, ...), and future branches (alpha, beta, ...), this creates a problem when we need to show images in the markdown content in the respective projects.
Currently, when including an image source like `https://github.com/TanStack/router/main/docs/assets/beta.png` it gets rendered from markdown "as-is" regardless of which …
> feat: support rewriting a doc's image source to the current branch

- app/components/DocsLayout.tsx
Since the Carbon block has been moved over to the right side below the Partners and Bytes blocks, we no longer need this 300px of bottom padding.
Before:
After:
> fix: remove the unused bottom padding on the side navigation on `<DocsLayout>`

- app/components/RedirectVersionBanner.tsx
> fix: broken mobile styling of the library redirect banner

- app/components/DocsLayout.tsx
Fixes #262 
Test URL: https://tanstack.com/query/latest/docs/framework/react/examples/simple
Before:
After:
> fix: docs content container should take up available height

- app/components/Markdown.tsx
On mobile, if you click a link to a heading within the markdown content, the heading with its content is hidden behind the mobile navbar.
To test, using a mobile phone (or more realistically the browser devtool) go to: https://tanstack.com/router/latest/docs/framework/react/start/api-routes, and click on the "Defining an API Route" link in the topics at the start of the page.
See the heading is hidden behind the navbar.
With this fix, it is no longer hidden.
> fix: scroll to a markdown heading is hidden when navigating on mobile

- app/components/ClientOnlySearchButton.tsx
- app/components/DocsLayout.tsx
- app/components/Orama.tsx
- app/routes/_libraries.tsx
- package.json
- pnpm-lock.yaml
Adds the new Orama SearchBox 🚀
> chore: add new orama search widget

- app/components/DocsLayout.tsx
- app/routes/_libraries.tsx
Fix Orama Search Widget open/close behavior
> hotfix: wrong open/close state

- app/routes/__root.tsx
- app/utils/seo.ts
Sharing https://tanstack.com/ in social networks (like linkedin) does not properly show the og:image in the preview.
<details><summary>See images</summary>
<p>
</p>
</details> 
Our current value is `/_build/assets/og-pGgYlhyc.png` but it seems [only absolute urls are valid](https://stackoverflow.com/a/9858694).
I'm not sure this works as I cannot reliably test it locally but I'd probably give it a try.
I think other pages may be affected but let's do it step by step (or if anyone has a better solution is welcome!)
> fix: use absolute url for og:image tag

- app/components/Markdown.tsx
A simple fix to prevent writing a `"\n"` line insert every time something is copied from a code-block.
> fix: remove additional new line insert when copying from code-blocks

- app/components/DocsLayout.tsx
This pr fixes some console errors due to the OramaSearchBox not being correctly initialized only when the parent component finished mounting.
NB. the `rel="noreferrer"` change is an eslint automatic change
> fix: only init OramaSearchBox when component mounts

- app/routes/_libraries.start.$version.index.tsx
Fixes a small error in the tanstack start landing page
> fix(start): typo on the landing page

- app/routes/_libraries.config.$version.index.tsx
- app/routes/_libraries.query.$version.index.tsx
- app/routes/_libraries.ranger.$version.index.tsx
PR for issue #289 
Fixing the line height on the library title pages that contain descender letters. (Query, Ranger, Config)
From:
To:
> fix: line height for descender letters on library title pages

- app/routes/_libraries.start.$version.index.tsx
Changed "We invite at to try" to "We invite all to try"
> fix(start): typo on Start landing page

- app/routes/_libraries.dedicated-support.tsx
> feat: add dedicated support note and bsky handles

- app/routes/_libraries/index.tsx
layout on mobile for stats is odd
current:
updated:
> chore: stats layout mobile update

- .prettierignore
- app/routes/_libraries/index.tsx
Could have sworn I updated this in the counter PR, just need to add utm query
> fix convex link

- app/components/RedirectVersionBanner.tsx
Currently, when trying to navigate to the latest version documentation via RedirectVersionBanner, users are incorrectly redirected to the library root page of the current version instead
- Added `to` prop in RedirectVersionBanner's Link component for latest version navigation
- Fixed by passing a `fullPath` (with `routeId`) from the latest `match`, though there might be a better solution given my limited familiarity with `tanstack/query`.
#310
> Fix: Resolve RedirectVersionBanner malfunction

- app/components/DocsLayout.tsx
- app/components/Orama.tsx
- app/routes/_libraries/route.tsx
- package.json
- pnpm-lock.yaml
This PR:
- Upgrades Orama components version. It fixes several styles issue and others.
- Uses dynamic theme so SearchBox colors matches the selected theme.
- Adds chat messages suggestions
> chore: upgrade searchbox / add suggestions / fix theme

- app/components/OpenSourceStats.tsx
- app/routes/_libraries/index.tsx
- convex/_generated/api.d.ts
- convex/stats.ts
- package.json
- pnpm-lock.yaml
- Restores counter animation
- Moves stats to separate component
- Reduces animation interval so NumberFlow can update continuously
After deploying this, go to the dashboard, navigate to your production instance, and run the `statsClearAndSync` function. You can also run it from your project locally:
```
npx convex run stats:clearAndSync --prod
```
> fix stats counter, move to separate file

- netlify.toml
- package.json
- pnpm-lock.yaml
**This PR adds `netlify.toml` with a custom production build command for Convex.**
If you don't want this approach, I can drop it and a team member with access can update the value directly in the Netlify dashboard. The config is only currently set to override the build command for production and nothing else, but can be extended as you see fit.
In either case, the CONVEX_DEPLOY_KEY env var will need to be set in the Netlify dashboard: https://docs.convex.dev/production/hosting/netlify#deploying-to-netlify
Also fixes the dev command so both vinxi and convex can exit properly on ctrl +c.
> update to @erquhart/convex-oss-stats@0.3.6

- app/routes/_libraries/index.tsx
The letter K on the landing page overflows, causing the end to be cut off. I've added some padding on the right to give it space to show the last bit of the K.
It seems to be the letter-spacing causing the overflow.
Before:
After:
> Fix K in "Tanstack" overflowing using padding

- .gitignore
- convex/_generated/api.d.ts
- convex/_generated/api.js
- convex/_generated/dataModel.d.ts
- convex/_generated/server.d.ts
- convex/_generated/server.js
This reverts commit 0eee823247a5a035082d86e440efe848268847b7.
> Revert "ignore generated convex code"

- app/styles/app.css
In the tanstack docs, each heading is a clickable anchor, but the clickable area also spans the whole width of the content area. An accidental click on this empty white space causes the heading and contents to suddenly yank to the top.
This PR limits the clickable area to just the heading text.
> fix: keep the empty space besides headings out of the clickable area

- app/routes/_libraries/router.$version.index.tsx
Change wording from "React" to "React and Solid"
Blocked by:
- https://github.com/TanStack/router/pull/3276
Related to:
- https://github.com/TanStack/router/pull/3481
> docs(router): "React and Solid"

- app/styles/app.css
- app/styles/app.generated.css
Fixes #349 
Courier New is hard to read, so it's better to give the default browser monospace font priority over it.
> Give default monospace priority over Courier New

- app/components/DocContainer.tsx
I noticed on some pages the width of the page container wasn't taking up all the space. You can see this in production on the [Classes/Effects](https://tanstack.com/store/latest/docs/reference/classes/effect) page in Store. Here it is in dev locally:
Turns out the `DocContainer.tsx` file didn't specify its width, only its max width. Setting the width to full fixes the issue:
> fix(layout): doc container width not taking up all available space

- app/routes/__root.tsx
- app/utils/usePrefersReducedMotion.ts
I made the background canvas respect user preferences regarding motion. A possible next step would be to add something similar to `<ThemeToggle />` and integrate it into the UI to allow users to manually override the system setting for motion preferences.
related #333
> feat: disable background animations for users preferring reduced motion

- app/components/Doc.tsx
- app/components/DocContainer.tsx
- app/components/TocMobile.tsx
- app/routes/_libraries/blog.$.tsx
Currently, on desktop, on the right side of the page, we have a persistent table of contents section that lists all the available headings within the markdown document. This section/component was hidden on mobile as its persistent nature would work on mobile.
This change, adds a mobile-optimized version of the above component, without the sticky/persistent nature.
Before:
After: 
With the section opened:
Also, looks surprisingly good in dark-mode as well:
> feat: add mobile version of the "table of contents"

- app/utils/sandbox.ts
when opening the start examples, it says it can't find
`./app/routes/__root.tsx`
The error can be repro'd here:
- https://tanstack.com/start/latest/docs/framework/react/examples/start-basic
It's correct the file is missing. It was moved to:
`./src/routes/__root.tsx`
... as part of:
- https://github.com/TanStack/router/pull/3712
> fix(codesandbox): open ./src instead of ./app on launch for start

- app/routes/$libraryId/$version.docs.framework.$framework.examples.$.tsx
- app/utils/documents.server.ts
- app/utils/sandbox.ts
Fixes an issue with the code-explorer dying when it couldn't resolve to child directories within the `examplePath`.
For example, when trying to start fetching the contents for `examples/react/pagination/src`, where the leaf `/src` directory did not exist, the whole application would simply fail.
To fix this, the contents will always be fetched from the contents API from the base of the `examplePath` (i.e. `examples/react/pagination`). From there on, once the contents have been fetched, the logic in `determineStartingFilePath` will resolve it to the correct starting file-path to have correct file opened in the explorer.
This results in a UI change, where the contents of the file-tree will differ from the existing implementation.
> [!IMPORTANT]
> The default opened/"starting file" will …
> fix(code-explorer): resolving starting path when not available

- app/components/InteractiveSandbox.tsx
You can notice how it's not taking all the remaining space due to `lg:rounded-lg` being there unnecessarily
Here is it with the removal. 
Though you can also see the bottom clips off due to `min-h-[80dvh]`, which happend before this. I just don't know if it's intentional or not.
> fix: interactive sandbox card not filling the whole card contents

- app/libraries/start.tsx
- app/routes/_libraries/start.$version.index.tsx
solid-start is out in experimental release
- https://github.com/TanStack/router/pull/3864
this enables the docs
> add solid to start docs selector and landing

- app/components/DocsLayout.tsx
Currently, when visiting a route, where the `config.json` has it configured to have the sidebar group be collapsed, it won't be opened even though its on the route 🤯
> fix: open the sidebar group by default if active

- app/routeTree.gen.ts
- app/routes/stats/index.tsx
Currently, when a user visits `tanstack.com/stats` they are shown a blank page since it assumes that `"stats"` is a TanStack library.
This change makes it so that when a user visits `tanstack.com/stats`, they shall be redirected to `tanstack.com/stats/npm`.
> add default redirect for `/stats`

- .gitignore
- app.config.ts
- app/blog/ag-grid-partnership.md
- app/blog/announcing-tanstack-form-v1.md
- app/blog/announcing-tanstack-query-v4.md
- app/blog/announcing-tanstack-query-v5.md
- app/blog/netlify-partnership.md
- app/blog/tanstack-router-typescript-performance.md
- app/blog/why-tanstack-start-and-router.md
- app/blog/why-tanstack-start-is-ditching-adapters.md
- app/routes/_libraries/blog.$.tsx
- app/routes/_libraries/blog.index.tsx
- app/utils/blog.ts
- content-collections.ts
- package.json
- pnpm-lock.yaml
- tsconfig.json
Based on [this X post](https://x.com/tannerlinsley/status/1918026872765727027), I've added [Content Collections](https://www.content-collections.dev/docs/quickstart/tanstack-start) to the blog page of [tanstack.com](https://tanstack.com/blog).
To summarize the change:
- Added Content Collections plugin to Vite
- Added Content Collections generated files to `.gitignore`
- Adjusted all `published` fields for articles to `YYYY-MM-DD`
- Adjusted `fetchFrontMatters` server function
- Removed `getPostList` utility function as, per my understanding, we don't need it anymore
Happy to hear feedback, as this is my small and first open-source contribution, and I've been really nervous before committing (had to fix stuff and force-push 4 times into my branch before opening PR).
> feat: use content collections for the blog

- app/components/Doc.tsx
This has to do with the "Edit on GitHub" link that we place at the moment of our markdown documents.
Previously, this link took the user to "view" the markdown document on GitHub.
With this change, the new link takes the user to a view designed by GitHub to encourage more native flows towards making edits.
If the user already has write-access on GitHub (which they most likely won't), then they can start making changes.
If not, the user will be asked to fork the repository, before they can begin making changes and opening a pull request (which they'd have to do anyways).
> fix: use the correct URL when the user clicks "Edit on Github"

- app.config.ts
In one of the new React minified versions, they changed `p(418)` to `n(418)`.
This change still allow `p(418)` backward compatibility as forward compatibility with the new React version which introduces the `n` function.
This change also introduces a replacement for 423 errors as they can also crash the runtime and malform the webpage.
> Update 418 and 423 error replacement

- src/components/DocsLayout.tsx
the Home and Frameworks links are using some relative linking, like `..` (which should be supported, but it breaks). This replaces that with full paths.
> fix Home and Frameworks links

- src/libraries/router.tsx
- src/libraries/start.tsx
> Include solid in tagline for start and router

- src/components/DocsLayout.tsx
Reverts changes introduced in:
the DocsLayout [here](https://github.com/TanStack/tanstack.com/pull/402/files#diff-dca09d1f9e869db78cabc35be2c9a352e85b828f790458c70348f18cb227f4bb)
[this commit](https://github.com/TanStack/tanstack.com/pull/405/files) for the Home and Frameworks pages.
> revert workarounds for links

- .tanstack-start/server-routes/routeTree.gen.ts
- src/routes/$libraryId/$version.docs.framework.$framework.{$}[.]md.tsx
- src/routes/$libraryId/$version.docs.{$}[.]md.tsx
This is PR lets the user access the markdown format of the documentation pages/guides, by adding a `.md` suffix to the end of the path.
With this change, the following (example) links would work as follows. 
- `/form/latest/docs/framework/react/guides/basic-concepts` serves React SSR'd version of the documentation.
- `/pacer/latest/docs/installation` serves React SSR'd version of the documentation.
- `/form/latest/docs/framework/react/guides/basic-concepts.md` serves the raw markdown for the documentation page.
- `/pacer/latest/docs/installation.md` serves the raw markdown for the documentation page.
This feature is useful for using the documentation with LLMs, and was inspired by `vite`:
> For every page you can get the original markdown by replacing the .html extension with .md - e.g.: …
> feat: directly serve library document markdown

- src/libraries/db.tsx
- src/routes/_libraries/db.$version.index.tsx
merge after https://github.com/TanStack/db/pull/115
> db: update links to load actual db docs

- src/components/BlankErrorBoundary.tsx
- src/components/OpenSourceStats.tsx
- src/routes/_libraries/index.tsx
- src/utils/partners.tsx
> fix: homepage errors and nested links

- src/components/ThemeProvider.tsx
- src/components/ThemeToggle.tsx
- src/routes/__root.tsx
- src/routes/_libraries/route.tsx
- tailwind.config.cjs
As discussed on Discord I removed the cookie logic in favor of localStorage to handle the theme (light, dark and auto)
It previously relied on zusatand, I replaced it with a react context in a separate commit, you can see both versions in this PR.
I think we should keep it simple and stay with the context but if we want to use zustand as it's already installed I can revert the second commit.
> feat: handle theme with localStorage

- src/libraries/start.tsx
- src/routes/$libraryId/$version.docs.index.tsx
- src/routes/_libraries/config.$version.index.tsx
- src/routes/_libraries/db.$version.index.tsx
- src/routes/_libraries/devtools.$version.index.tsx
- src/routes/_libraries/form.$version.index.tsx
- src/routes/_libraries/maintainers.tsx
- src/routes/_libraries/pacer.$version.index.tsx
- src/routes/_libraries/query.$version.index.tsx
- src/routes/_libraries/ranger.$version.index.tsx
- src/routes/_libraries/route.tsx
- src/routes/_libraries/router.$version.index.tsx
- src/routes/_libraries/start.$version.index.tsx
- src/routes/_libraries/store.$version.index.tsx
- src/routes/_libraries/table.$version.index.tsx
- src/routes/_libraries/virtual.$version.index.tsx
All the "get started" links are plain strings, not really typesafe in a tanstack style. This PR addresses it.
Also relative navigation does not infers the `libraryId` on pages where the param is defined, this might be material for an issue on Router though.
---
There are 101 typescript errors and 56 eslint warnings in the repo, I might take on this crusade step by step and get rid of them.
> fix: raw links

- src/components/OpenSourceStats.tsx
- src/routes/_libraries/config.$version.index.tsx
- src/routes/_libraries/db.$version.index.tsx
- src/routes/_libraries/devtools.$version.index.tsx
- src/routes/_libraries/form.$version.index.tsx
- src/routes/_libraries/index.tsx
- src/routes/_libraries/pacer.$version.index.tsx
- src/routes/_libraries/query.$version.index.tsx
- src/routes/_libraries/ranger.$version.index.tsx
- src/routes/_libraries/router.$version.index.tsx
- src/routes/_libraries/start.$version.index.tsx
- src/routes/_libraries/store.$version.index.tsx
- src/routes/_libraries/table.$version.index.tsx
- src/routes/_libraries/virtual.$version.index.tsx
Fixes stat counters on home and library pages so they load instantly.
Follow up from https://github.com/TanStack/tanstack.com/pull/465#issuecomment-3221934547
> fix: render stat counters on client load

- src/routes/stats/npm/-comparisons.ts
This PR adds comparisons for **Documentation** (could also be Static Site Generators, but that may overlaps with "Frameworks").
Currently included: Vitepress, Docusaurus, Vocs, Astro Starlight, Nextra, and Fumadocs.
filling the last corner:
> Stats: Add comparisons for docs frameworks

- src/blog/tanstack-db-0.1-the-embedded-client-database-for-tanstack-query.md
There are two links to `https://tanstack.com/db/latest/docs/guides/collection-options-creator` that were missing the `/guides` path.
> fix: broken URL in TanStack DB blog post

- src/components/Navbar.tsx
- src/routes/__root.tsx
- src/styles/app.css
Adds `scroll-padding-top` to accommodate for sticky header.
Otherwise all anchor links are scrolled too far and user would not see the header that was linked to as it's behind the header.
https://github.com/user-attachments/assets/bacb976e-1edc-4252-822b-92cb26c2074b
> fix: add scroll-padding to accommodate for the sticky header height

- src/components/Doc.tsx
fixes issue where the "edit on github" link stretches across the entire width. noticed this when i got redirected randomly to github when i was navigating the docs.
before:
after:
> fix: change doc footer from block to flex
