TanStack/tanstack.com

- app/routes/router/v4/index.tsx
Hi @tannerlinsley was going through the docs and realised that there were some slight UI issue, great work btw! really enjoy the talks u have given about the stack
Before:
After:
> chore: update router docs to include missing space

- README.md
I updated README since it decided to use yarn instead of npm.
> Update cli script from npm to yarn in README

- app/styles/app.css
Fixes missing semi colon from #38
> Add missing semi colon

- app/components/Footer.tsx
- app/routes/blog/$.tsx
- app/routes/index.tsx
- app/routes/query/v4/docs.tsx
- app/routes/query/v4/docs/$.tsx
- app/routes/query/v4/index.tsx
- app/routes/router/v1/docs.tsx
- app/routes/router/v1/docs/$.tsx
- app/routes/router/v1/index.tsx
- app/routes/sponsor-login.tsx
- app/routes/table/v8/docs.tsx
- app/routes/table/v8/docs/$.tsx
- app/routes/table/v8/index.tsx
- app/routes/virtual/v3/docs.tsx
- app/routes/virtual/v3/docs/$.tsx
- app/routes/virtual/v3/index.tsx
- app/server/discord-github.ts
- app/server/github.ts
Thanks for the new router (and all of your other numerous contributions to open source), really cool! 🙌
Just a quick PR to fix the casing of GitHub.
> Fix casing of GitHub

- app/components/Docs.tsx
- app/routes/query/v4/index.tsx
Closes: https://github.com/TanStack/query/issues/4660
> docs: fix links in query docs

- app/components/Footer.tsx
- app/components/LinkOrA.tsx
- app/routes/index.tsx
Added target _blank on external links for improve user experience and accesibility.
This way the user will not leave the website after clicking on a external link, thus improving their experience.
> Add target _blank on external links for improve user experience #346

- app/routes/query/$version.tsx
- app/routes/query/$version/docs/$framework/examples/$.tsx
Should go after https://github.com/TanStack/query/pull/4890
> feat: query v3 docs compat

- app/routes/virtual/v3/index.tsx
> Added blank-space between words

- app/blog/announcing-tanstack-query-v5.md
Fixed two typos on October 17 2023 blog post.
Deleted one word in second paragraph to improve grammar
> [fix-typo]Update announcing-tanstack-query-v5.md

- app/components/Docs.tsx
This PR fixes the center column collapsing as reported here: https://github.com/TanStack/tanstack.com/issues/106
> Fix center column collapsing

- app/components/Docs.tsx
This PR fixes collapsed content for narrower views.
Before:
After:
> Fix collapsing content

- app/images/angular-logo.svg
> Update Angular logo

- app/routes/query.$version.docs.$framework.$.tsx
Fixes https://github.com/TanStack/tanstack.com/issues/85
> Fix endless redirects for non-react frameworks in query v3

- app/projects/form.tsx
- app/projects/store.tsx
Fixes https://github.com/TanStack/tanstack.com/issues/146
> fix: Regression - the form framework picker doesn't work properly

- app.config.mjs
- tsr + vinxi init
- checkpoint
- Fix rebase
- update deps
- match.handle => match.staticData
- checkpoint
- link ssr and client router
> add link between ssr & client router for assets

- app/projects/table.ts
- app/routes/router.$.tsx
- app/routes/table.$.tsx
- app/routes/table.$version.docs.$.tsx
- app/routes/table.$version.tsx
- app/utils/handleRedirects.server.ts
Fixes the old manual version redirects don't work as expected  (https://github.com/TanStack/tanstack.com/issues/164).
> Fix old manual redirects

- app/routes/query.$version._index.tsx
Angular was not mentioned on https://tanstack.com/query/v5
CC @tkdodo @arnoud-dv
> angular query mentioned on https://tanstack.com/query/v5

- app/server/airtable.ts
- app/server/sponsors.ts
- app/server/tiers.ts
It appears that our Airtable API has expired and Tanner isn't around at the moment. This PR should unblock us for now until we can re-eval
> fix: temporarily remove airtable to fix prod

- app/projects/config.ts
- app/routes/_index.tsx
- app/routes/config.$.tsx
- app/routes/config.$version._index.tsx
- app/routes/config.$version.docs.$.tsx
- app/routes/config.$version.docs._index.tsx
- app/routes/config.$version.docs.tsx
- app/routes/config.$version.tsx
- app/routes/config.tsx
https://github.com/TanStack/config
> feat: Add routes for TanStack Config

- app/images/lit-logo.svg
- app/projects/form.ts
To prep for https://github.com/TanStack/form/pull/577/ to be merged, this PR is being opened to support showing Lit and the Lit logo on the Form website
> feat: add Lit to Form dropdown selector

- app/projects/form.ts
- app/routes/_index.tsx
- app/routes/form.$version._index.tsx
- app/routes/form.tsx
This preps for https://github.com/TanStack/form/pull/627 imminent release
> feat: add angular to TanStack Form pages

- app/routes/form.$version.docs.framework.$framework.examples.$.tsx
- app/routes/query.$version.docs.framework.$framework.examples.$.tsx
- app/routes/ranger.$version.docs.framework.$framework.examples.$.tsx
- app/routes/router.$version.docs.framework.$framework.examples.$.tsx
- app/routes/store.$version.docs.framework.$framework.examples.$.tsx
- app/routes/table.$version.docs.framework.$framework.examples.$.tsx
- app/routes/virtual.$version.docs.framework.$framework.examples.$.tsx
> fix angular stackblitz examples

- app/components/DocsLayout.tsx
- package.json
- pnpm-lock.yaml
This PR introduces the first batch of fixes for the Orama Searchbox. Opening this as a draft since @g-francesca is working on a few other fixes.
> chore: updates Orama to its latest version

- app/components/DocsCalloutQueryGG.tsx
- app/components/QueryGGBannerSale.tsx
This PR extends sale through June 6th
> Extend time for launch sale

- app/routes/_libraries.table.$version.index.tsx
Add Lit as supported framework to the main page.
> feat(table): add Lit as supported framework in main page of Table

- app/routes/_libraries.start.$version.index.tsx
I haven't touched these repos before or had the pnpm setup to test this, but thought I would shoot my shot at correcting the route causing a 500 based on the other links on the page 😆
> fix: update getting started route in tanstack start landing page

- app/routes/_libraries.virtual.$version.index.tsx
```diff
- Tanstack Table's
+ Tanstack Virtual's
```
> docs: update _libraries.virtual.$version.index.tsx

- app/components/DocsLayout.tsx
- app/styles/app.css
Wanted to print out a couple of pages, but some things are not too print friendly. Hidden overlayed things and changed gradient colored text, since it's invisible otherwise.
> Improve print layout

- package.json
- pnpm-lock.yaml
This reverts commit 2060a8c75666309cfc084740a404cc7af17dd5ba.
> fix: Revert "update vinxi/vite"

- package.json
- pnpm-lock.yaml
- improve scraping based contributor/dependent stat accuracy
- improves server and client component performance (faster sync times)
> update to @erquhart/convex-oss-stats@0.3.3

- app/routes/_libraries/start.$version.index.tsx
- Fix missing "to" in "invite you to provide"
- Remove duplicate "help" word
- Improve sentence structure with proper conjunction
> docs: fix grammar in "When can I use it?" section

- app/libraries/start.tsx
Use same order of library sublinks as all other libraries
> refactor: Reorder TSS links

- package.json
- scripts/link.js
Follow up to
- https://github.com/TanStack/router/pull/3549
cc @schiller-manuel
> Remove react-cross-context

- .gitignore
- package.json
- pnpm-lock.yaml
Remove `vite` since `vinxi` needs to have full control over it.
> chore: remove vite

- src/components/MaintainerCard.tsx
- src/libraries/maintainers.ts
- src/routeTree.gen.ts
- src/routes/$libraryId/$version.docs.contributors.tsx
- src/routes/_libraries/maintainers.tsx
- src/routes/_libraries/paid-support.tsx
- src/routes/_libraries/route.tsx
- src/server/github.ts
- src/utils/docs.ts
> add new root maintainers page with fun filtering and sorting
